// -----------------------------------------------------------------------------
// This file is part of Silicium
//
// Copyright (C) Dirk W. Hoffmann. www.dirkwhoffmann.de
// Licensed under the Mozilla Public License v2
//
// See https://mozilla.org/MPL/2.0 for license information
// -----------------------------------------------------------------------------

#pragma once

#include "debug.h"

// VER_MAJOR and friends, generated by CMake from Apps/version.h.in. Stated in
// Apps/CMakeLists.txt so that the build system and the code share one version
// rather than each carrying its own copy.
#include "version.h"

//
// Release settings
//

#ifdef NDEBUG
static constexpr bool releaseBuild = 1;
static constexpr bool debugBuild = 0;
#else
static constexpr bool releaseBuild = 0;
static constexpr bool debugBuild = 1;
#endif

#ifdef __APPLE__
static constexpr bool macOS = 1;
#else
static constexpr bool macOS = 0;
#endif

#ifdef __EMSCRIPTEN__
static constexpr bool wasmBuild = 1;
#else
static constexpr bool wasmBuild = 0;
#endif
